"""extend_uploaded_files_s3

Revision ID: 852e13749003
Revises: bc3754c00156
Create Date: 2026-07-09 09:36:53.860526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852e13749003'
down_revision: Union[str, Sequence[str], None] = 'bc3754c00156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('storage_provider', sa.String(length=50), nullable=False))
    op.add_column('uploaded_files', sa.Column('s3_object_key', sa.String(length=500), nullable=True))
    op.add_column('uploaded_files', sa.Column('bucket_name', sa.String(length=255), nullable=True))
    op.add_column('uploaded_files', sa.Column('storage_url', sa.String(length=1000), nullable=True))
    op.add_column('uploaded_files', sa.Column('etag', sa.String(length=255), nullable=True))
    op.add_column('uploaded_files', sa.Column('upload_completed', sa.Boolean(), nullable=False))
    op.add_column('uploaded_files', sa.Column('storage_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_uploaded_files_storage_provider'), 'uploaded_files', ['storage_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_storage_provider'), table_name='uploaded_files')
    op.drop_column('uploaded_files', 'storage_size')
    op.drop_column('uploaded_files', 'upload_completed')
    op.drop_column('uploaded_files', 'etag')
    op.drop_column('uploaded_files', 'storage_url')
    op.drop_column('uploaded_files', 'bucket_name')
    op.drop_column('uploaded_files', 's3_object_key')
    op.drop_column('uploaded_files', 'storage_provider')
    # ### end Alembic commands ###
