"""add_document_processing_tables

Revision ID: aa14dfbd2952
Revises: 852e13749003
Create Date: 2026-07-09 10:27:10.939176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa14dfbd2952'
down_revision: Union[str, Sequence[str], None] = '852e13749003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('processing_status', sa.String(length=50), nullable=False))
    op.add_column('uploaded_files', sa.Column('processing_progress', sa.Integer(), nullable=False))
    op.add_column('uploaded_files', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('uploaded_files', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('uploaded_files', sa.Column('text_extracted', sa.Boolean(), nullable=False))
    op.add_column('uploaded_files', sa.Column('ocr_completed', sa.Boolean(), nullable=False))
    op.add_column('uploaded_files', sa.Column('last_processed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'last_processed')
    op.drop_column('uploaded_files', 'ocr_completed')
    op.drop_column('uploaded_files', 'text_extracted')
    op.drop_column('uploaded_files', 'page_count')
    op.drop_column('uploaded_files', 'document_type')
    op.drop_column('uploaded_files', 'processing_progress')
    op.drop_column('uploaded_files', 'processing_status')
    # ### end Alembic commands ###
